from django.urls import path
from AppCoder import views
urlpatterns = [
    path('', views.inicio,name="Inicio"),
    path('Cursos', views.cursos),
    path('Estudiantes', views.estudiantes),
    path('Profesores', views.profesores),
    path('Entregables', views.entregables),
    path('CreacionProfesor',views.CreacionProfesor),
    path('BuscadorProfesor',views.BuscadorProfesor),
    path('CreacionEntregables',views.CreacionEntregables),
    path('BuscadorEntregables',views.BuscadorEntregables),
    path('CreacionEstudiante',views.CreacionEstudiantes),
    path('BuscadorEstudiante',views.BuscadorEstudiantes),
    path('CreacionCurso',views.CreacionCurso),
    path('BuscadorCurso',views.BuscadorCurso),
    path('curso/list',views.CursoList.as_view(), name="ListC"),
    path(r'^(?P<pk>\d+)$',views.CursoDetalle.as_view(), name="DetailC"),
    path(r'^editar/(?P<pk>\d+)$',views.CursoUpdate.as_view(), name="EditC"),
    path(r'^borrar/(?P<pk>\d+)$',views.CursoDelete.as_view(), name="DeleteC"),
    path('estudiante/list',views.EstudianteList.as_view(), name="ListE"),
    path('estudiante_detail/<pk>',views.EstudianteDetalle.as_view(), name="DetailE"),
    path('estudiante_edit/<pk>',views.EstudianteUpdate.as_view(), name="EditE"),
    path('estudiante_delete/<pk>',views.EstudianteDelete.as_view(), name="DeleteE"),
    path('profesor/list',views.ProfesorList.as_view(), name="ListP"),
    path('profesor_detail/<pk>',views.ProfesorDetalle.as_view(), name="DetailP"),
    path('profesor_edit/<pk>',views.ProfesorUpdate.as_view(), name="EditP"),
    path('profesor_delete/<pk>',views.ProfesorDelete.as_view(), name="DeleteP"),
    path('entregable/list',views.EntregableList.as_view(), name="ListEn"),
    path('entregable_detail/<pk>',views.EntregableDetalle.as_view(), name="DetailEn"),
    path('entregable_edit/<pk>',views.EntregableUpdate.as_view(), name="EditEn"),
    path('entregable_delete/<pk>',views.EntregableDelete.as_view(), name="DeleteEn"),
    path('login',views.AdminLoginView.as_view(), name="Login"),
    path('register',views.SingUpView.as_view(), name="Register"),
    path('logout',views.AdminLogoutView.as_view(), name="Logout"),
    path('editarPerfil',views.editarPerfil, name="EditarPerfil"),
    path('Dudas', views.dudas),
    path('CrearDudas',views.CreacionDudas),
    path('dudas/list',views.DudaList.as_view(), name="ListD"),
    path('duda_detail/<pk>',views.DudaDetalle.as_view(), name="DetailD"),
    path('duda_edit/<pk>',views.DudaUpdate.as_view(), name="EditD"),
    path('duda_delete/<pk>',views.DudaDelete.as_view(), name="DeleteD"),
    path('VerPerfil',views.VerPerfil, name="VerPerfil"),
]
