# Generated by Django 4.1.2 on 2022-12-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
